# Generated by Django 4.2.1 on 2023-05-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers_Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zestawu', models.CharField(blank=True, max_length=2, null=True)),
                ('plec', models.CharField(blank=True, max_length=2, null=True)),
                ('wiek', models.CharField(blank=True, max_length=2, null=True)),
                ('daltonizm', models.CharField(blank=True, max_length=10, null=True)),
                ('Happiness_1', models.TextField(blank=True, null=True)),
                ('Happiness_2', models.TextField(blank=True, null=True)),
                ('Happiness_3', models.TextField(blank=True, null=True)),
                ('Happiness_4', models.TextField(blank=True, null=True)),
                ('Happiness_5', models.TextField(blank=True, null=True)),
                ('Anger_1', models.TextField(blank=True, null=True)),
                ('Anger_2', models.TextField(blank=True, null=True)),
                ('Anger_3', models.TextField(blank=True, null=True)),
                ('Anger_4', models.TextField(blank=True, null=True)),
                ('Anger_5', models.TextField(blank=True, null=True)),
                ('Sadness_1', models.CharField(max_length=20)),
                ('Sadness_2', models.CharField(max_length=20)),
                ('Sadness_3', models.CharField(max_length=20)),
                ('Sadness_4', models.CharField(max_length=20)),
                ('Sadness_5', models.CharField(max_length=20)),
                ('Surprise_1', models.CharField(max_length=20)),
                ('Surprise_2', models.CharField(max_length=20)),
                ('Surprise_3', models.CharField(max_length=20)),
                ('Surprise_4', models.CharField(max_length=20)),
                ('Surprise_5', models.CharField(max_length=20)),
                ('Neutral_1', models.CharField(max_length=20)),
                ('Neutral_2', models.CharField(max_length=20)),
                ('Neutral_3', models.CharField(max_length=20)),
                ('Neutral_4', models.CharField(max_length=20)),
                ('Neutral_5', models.CharField(max_length=20)),
                ('Disgust_1', models.CharField(max_length=20)),
                ('Disgust_2', models.CharField(max_length=20)),
                ('Disgust_3', models.CharField(max_length=20)),
                ('Disgust_4', models.CharField(max_length=20)),
                ('Disgust_5', models.CharField(max_length=20)),
            ],
        ),
    ]
