# Generated by Django 4.2.1 on 2023-05-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers_survey',
            name='daltonizm',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='plec',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
