# Generated by Django 4.2.1 on 2023-11-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers_survey',
            old_name='Anger_1',
            new_name='Song_1_colors',
        ),
        migrations.RenameField(
            model_name='answers_survey',
            old_name='Anger_2',
            new_name='Song_1_colors_emotion',
        ),
        migrations.RenameField(
            model_name='answers_survey',
            old_name='Anger_3',
            new_name='Song_2_colors',
        ),
        migrations.RenameField(
            model_name='answers_survey',
            old_name='Anger_4',
            new_name='Song_2_colors_emotion',
        ),
        migrations.RenameField(
            model_name='answers_survey',
            old_name='Anger_5',
            new_name='Song_3_colors',
        ),
        migrations.RenameField(
            model_name='answers_survey',
            old_name='Happiness_1',
            new_name='Song_3_colors_emotion',
        ),
        migrations.RenameField(
            model_name='answers_survey',
            old_name='Happiness_2',
            new_name='Song_4_colors',
        ),
        migrations.RenameField(
            model_name='answers_survey',
            old_name='Happiness_3',
            new_name='Song_4_colors_emotion',
        ),
        migrations.RenameField(
            model_name='answers_survey',
            old_name='Happiness_4',
            new_name='Song_5_colors',
        ),
        migrations.RenameField(
            model_name='answers_survey',
            old_name='Happiness_5',
            new_name='Song_5_colors_emotion',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Disgust_1',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Disgust_2',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Disgust_3',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Disgust_4',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Disgust_5',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Neutral_1',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Neutral_2',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Neutral_3',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Neutral_4',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Neutral_5',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Sadness_1',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Sadness_2',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Sadness_3',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Sadness_4',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Sadness_5',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Surprise_1',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Surprise_2',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Surprise_3',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Surprise_4',
        ),
        migrations.RemoveField(
            model_name='answers_survey',
            name='Surprise_5',
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_1_colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_1_colors_emotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_2_colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_2_colors_emotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_3_colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_3_colors_emotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_4_colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_4_colors_emotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_5_colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_5_colors_emotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_6_colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers_survey',
            name='Speech_6_colors_emotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='plec',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
