# Generated by Django 4.2.1 on 2023-05-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_answers_survey_daltonizm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers_survey',
            name='daltonizm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='plec',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
