# Generated by Django 4.2.1 on 2023-11-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_anger_1_answers_survey_song_1_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers_survey',
            name='nr_zestawu',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
