# Generated by Django 4.2.1 on 2023-05-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answers_survey_daltonizm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers_survey',
            name='Disgust_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Disgust_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Disgust_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Disgust_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Disgust_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Neutral_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Neutral_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Neutral_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Neutral_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Neutral_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Sadness_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Sadness_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Sadness_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Sadness_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Sadness_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Surprise_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Surprise_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Surprise_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Surprise_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers_survey',
            name='Surprise_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
